blueprint:
  name: Group Based Actionable Notification
  description: >-
    A script that sends an actionable notification
  domain: script
  input:
    notify_device:
      name: Group1 to notify
      description: Devices need to run the official Home Assistant app to receive notifications.
      selector:
        service:
    title:
      name: "Title"
      description: "The title of the button shown in the notification."
      default: ""
      selector:
        text:
    message:
      name: "Message"
      description: "The message body"
      selector:
        text:
    confirm_text:
      name: "Action 1"
      description: "Text to show on the first action button"
      default: "Confirm"
      selector:
        text:
    confirm_action:
      name: "Action 1 Action"
      description: "Action to run when first action is selected"
      default: []
      selector:
        action:
    dismiss_text:
      name: "Action 2"
      description: "Text to show on the second action button"
      default: "Dismiss"
      selector:
        text:
    dismiss_action:
      name: "Action 2 Action"
      description: "Action to run when second action is selected"
      default: []
      selector:
        action:

mode: restart

sequence:
  - alias: "Send notification"
    service: notify.household
    data:
      title: !input title
      message: !input message
      data:
        actions:
          - action: "CONFIRM"
            title: !input confirm_text
          - action: "DISMISS"
            title: !input dismiss_text
  - alias: "Awaiting response"
    wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
  - choose:
      - conditions: "{{ wait.trigger.event.data.action == 'CONFIRM' }}"
        sequence: !input confirm_action
      - conditions: "{{ wait.trigger.event.data.action == 'DISMISS' }}"
        sequence: !input dismiss_action